version: '3.9'

services:
  db:
    image: postgres
    container_name: djangoAPI_postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: djangoAPI_pgadmin4
    # user: "${UID}:${GID}" #pgAdmin container runs with the same user as the host. specially for folder creation etc
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "8008:8008"
    depends_on:
      - db

  django_backend:
    build: .
    container_name: djangoAPI_app
    ports:
      - '8888:8888'
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - db

volumes:
  pg_data: